// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: provider.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelProvider_GetInfo_FullMethodName                  = "/plugin.ModelProvider/GetInfo"
	ModelProvider_ListModels_FullMethodName               = "/plugin.ModelProvider/ListModels"
	ModelProvider_GenerateCompletion_FullMethodName       = "/plugin.ModelProvider/GenerateCompletion"
	ModelProvider_GenerateCompletionStream_FullMethodName = "/plugin.ModelProvider/GenerateCompletionStream"
	ModelProvider_CallTool_FullMethodName                 = "/plugin.ModelProvider/CallTool"
	ModelProvider_GenerateEmbedding_FullMethodName        = "/plugin.ModelProvider/GenerateEmbedding"
)

// ModelProviderClient is the client API for ModelProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelProviderClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*ProviderInfo, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	GenerateCompletion(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error)
	GenerateCompletionStream(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompletionChunk], error)
	CallTool(ctx context.Context, in *ToolCallRequest, opts ...grpc.CallOption) (*ToolCallResponse, error)
	GenerateEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
}

type modelProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewModelProviderClient(cc grpc.ClientConnInterface) ModelProviderClient {
	return &modelProviderClient{cc}
}

func (c *modelProviderClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*ProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderInfo)
	err := c.cc.Invoke(ctx, ModelProvider_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ModelProvider_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderClient) GenerateCompletion(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, ModelProvider_GenerateCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderClient) GenerateCompletionStream(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompletionChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModelProvider_ServiceDesc.Streams[0], ModelProvider_GenerateCompletionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompletionRequest, CompletionChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelProvider_GenerateCompletionStreamClient = grpc.ServerStreamingClient[CompletionChunk]

func (c *modelProviderClient) CallTool(ctx context.Context, in *ToolCallRequest, opts ...grpc.CallOption) (*ToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolCallResponse)
	err := c.cc.Invoke(ctx, ModelProvider_CallTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderClient) GenerateEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, ModelProvider_GenerateEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelProviderServer is the server API for ModelProvider service.
// All implementations must embed UnimplementedModelProviderServer
// for forward compatibility.
type ModelProviderServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*ProviderInfo, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	GenerateCompletion(context.Context, *CompletionRequest) (*CompletionResponse, error)
	GenerateCompletionStream(*CompletionRequest, grpc.ServerStreamingServer[CompletionChunk]) error
	CallTool(context.Context, *ToolCallRequest) (*ToolCallResponse, error)
	GenerateEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	mustEmbedUnimplementedModelProviderServer()
}

// UnimplementedModelProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelProviderServer struct{}

func (UnimplementedModelProviderServer) GetInfo(context.Context, *GetInfoRequest) (*ProviderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedModelProviderServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelProviderServer) GenerateCompletion(context.Context, *CompletionRequest) (*CompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCompletion not implemented")
}
func (UnimplementedModelProviderServer) GenerateCompletionStream(*CompletionRequest, grpc.ServerStreamingServer[CompletionChunk]) error {
	return status.Error(codes.Unimplemented, "method GenerateCompletionStream not implemented")
}
func (UnimplementedModelProviderServer) CallTool(context.Context, *ToolCallRequest) (*ToolCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedModelProviderServer) GenerateEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateEmbedding not implemented")
}
func (UnimplementedModelProviderServer) mustEmbedUnimplementedModelProviderServer() {}
func (UnimplementedModelProviderServer) testEmbeddedByValue()                       {}

// UnsafeModelProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelProviderServer will
// result in compilation errors.
type UnsafeModelProviderServer interface {
	mustEmbedUnimplementedModelProviderServer()
}

func RegisterModelProviderServer(s grpc.ServiceRegistrar, srv ModelProviderServer) {
	// If the following call panics, it indicates UnimplementedModelProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelProvider_ServiceDesc, srv)
}

func _ModelProvider_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvider_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProvider_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvider_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProvider_GenerateCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderServer).GenerateCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvider_GenerateCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderServer).GenerateCompletion(ctx, req.(*CompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProvider_GenerateCompletionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModelProviderServer).GenerateCompletionStream(m, &grpc.GenericServerStream[CompletionRequest, CompletionChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelProvider_GenerateCompletionStreamServer = grpc.ServerStreamingServer[CompletionChunk]

func _ModelProvider_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvider_CallTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderServer).CallTool(ctx, req.(*ToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProvider_GenerateEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderServer).GenerateEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvider_GenerateEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderServer).GenerateEmbedding(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelProvider_ServiceDesc is the grpc.ServiceDesc for ModelProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.ModelProvider",
	HandlerType: (*ModelProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _ModelProvider_GetInfo_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ModelProvider_ListModels_Handler,
		},
		{
			MethodName: "GenerateCompletion",
			Handler:    _ModelProvider_GenerateCompletion_Handler,
		},
		{
			MethodName: "CallTool",
			Handler:    _ModelProvider_CallTool_Handler,
		},
		{
			MethodName: "GenerateEmbedding",
			Handler:    _ModelProvider_GenerateEmbedding_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateCompletionStream",
			Handler:       _ModelProvider_GenerateCompletionStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "provider.proto",
}
