name = "dojo-telemetry"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "dojo-telemetry"
database_id = "d7b1f9d6-c9dc-4d55-87fe-f01163e3515a"
migrations_dir = "migrations"
