-- ============================================================================
-- Migration: v0.0.20 (The Compassionate Companion)
-- ============================================================================
-- Migration Date: February 1, 2026
-- Migration Version: 20260201_v0.0.20
-- 
-- **REQUIRES: v0.0.19 as base version**
-- Base Version: v0.0.19 (Migration: 20260201_v0.0.19)
-- Target Database: SQLite at .dojo/memory.db
--
-- This migration adds:
-- - Context Engine: Project suggestions, action patterns, activity logging
-- - Goal System: Goals, steps, artifact links
-- - Judgment Layer: Decision tracking, quiet hours
--
-- IMPORTANT NOTES:
-- - This migration is atomic (transaction-wrapped) and can be safely retried
-- - All operations preserve existing data
-- - New tables support proactive intelligence and goal tracking
-- - Default behavior: Suggestions disabled (opt-in via suggestion_enabled)
-- ============================================================================

-- Enable foreign key constraints
PRAGMA foreign_keys = ON;

-- Begin transaction to ensure atomic migration
BEGIN TRANSACTION;

-- ============================================================================
-- Migration Version Tracking
-- ============================================================================

-- Record this migration
INSERT INTO schema_migrations (version, applied_at, description)
VALUES ('20260201_v0.0.20', datetime('now'), 'v0.0.20: The Compassionate Companion - Context Engine, Goal System, Judgment Layer');

-- ============================================================================
-- Context Engine: Project Suggestions
-- ============================================================================

-- Stores suggestions generated by the context engine
-- Types: dormancy (7+ days no activity), stuck (repeated edits without progress),
--        blockage (tasks stuck in status), pattern (learned workflow patterns),
--        resource (relevant external resources found)
CREATE TABLE IF NOT EXISTS project_suggestions (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('dormancy', 'stuck', 'blockage', 'pattern', 'resource')),
    title TEXT NOT NULL,
    description TEXT,
    confidence REAL DEFAULT 0.5 CHECK(confidence >= 0.0 AND confidence <= 1.0),
    status TEXT DEFAULT 'pending' CHECK(status IN ('pending', 'accepted', 'dismissed')),
    created_at DATETIME NOT NULL,
    dismissed_at DATETIME,
    accepted_at DATETIME,
    feedback TEXT,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_suggestions_project ON project_suggestions(project_id);
CREATE INDEX IF NOT EXISTS idx_suggestions_status ON project_suggestions(status);
CREATE INDEX IF NOT EXISTS idx_suggestions_confidence ON project_suggestions(confidence DESC);
CREATE INDEX IF NOT EXISTS idx_suggestions_created ON project_suggestions(created_at DESC);

-- ============================================================================
-- Context Engine: Action Patterns
-- ============================================================================

-- Learns workflow patterns: "After action X, user typically does action Y"
-- Example: "After creating diagram, user typically writes summary"
-- Frequency and recency inform confidence scoring
CREATE TABLE IF NOT EXISTS action_patterns (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    before_action TEXT NOT NULL,
    after_action TEXT NOT NULL,
    frequency INTEGER DEFAULT 1,
    last_seen DATETIME NOT NULL,
    confidence REAL DEFAULT 0.5 CHECK(confidence >= 0.0 AND confidence <= 1.0),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_patterns_project ON action_patterns(project_id);
CREATE INDEX IF NOT EXISTS idx_patterns_frequency ON action_patterns(frequency DESC);
CREATE INDEX IF NOT EXISTS idx_patterns_confidence ON action_patterns(confidence DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_patterns_unique ON action_patterns(project_id, before_action, after_action);

-- ============================================================================
-- Context Engine: Project Activity Log
-- ============================================================================

-- Tracks project activity for dormancy/stuck detection
-- Activity types: file_edit, artifact_create, artifact_update, goal_update, session_start
CREATE TABLE IF NOT EXISTS project_activity_log (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    activity_type TEXT NOT NULL CHECK(activity_type IN ('file_edit', 'artifact_create', 'artifact_update', 'goal_update', 'session_start')),
    file_path TEXT,
    artifact_id TEXT,
    goal_id TEXT,
    created_at DATETIME NOT NULL,
    metadata TEXT CHECK(metadata IS NULL OR json_valid(metadata)),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (artifact_id) REFERENCES artifacts(id) ON DELETE SET NULL,
    FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_activity_project ON project_activity_log(project_id);
CREATE INDEX IF NOT EXISTS idx_activity_created ON project_activity_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_type ON project_activity_log(activity_type);
CREATE INDEX IF NOT EXISTS idx_activity_project_created ON project_activity_log(project_id, created_at DESC);

-- ============================================================================
-- Goal System: Goals
-- ============================================================================

-- User-defined goals with deadlines and status tracking
-- Status: active (working on), completed (achieved), paused (on hold), cancelled (abandoned)
CREATE TABLE IF NOT EXISTS goals (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    deadline DATETIME,
    status TEXT DEFAULT 'active' CHECK(status IN ('active', 'completed', 'paused', 'cancelled')),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    completed_at DATETIME,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_goals_project ON goals(project_id);
CREATE INDEX IF NOT EXISTS idx_goals_status ON goals(status);
CREATE INDEX IF NOT EXISTS idx_goals_deadline ON goals(deadline);
CREATE INDEX IF NOT EXISTS idx_goals_updated ON goals(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_goals_project_status ON goals(project_id, status);

-- ============================================================================
-- Goal System: Goal Steps
-- ============================================================================

-- Decomposition of goals into trackable steps
-- Steps ordered by order_index for sequential progress
CREATE TABLE IF NOT EXISTS goal_steps (
    id TEXT PRIMARY KEY,
    goal_id TEXT NOT NULL,
    title TEXT NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    completed_at DATETIME,
    order_index INTEGER NOT NULL,
    FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_steps_goal ON goal_steps(goal_id, order_index);
CREATE INDEX IF NOT EXISTS idx_steps_completed ON goal_steps(completed);

-- ============================================================================
-- Goal System: Goal-Artifact Links
-- ============================================================================

-- Links artifacts to goals/steps for progress tracking
-- Allows answering "This artifact advances goal X, step Y"
CREATE TABLE IF NOT EXISTS goal_artifact_links (
    id TEXT PRIMARY KEY,
    goal_id TEXT NOT NULL,
    artifact_id TEXT NOT NULL,
    step_id TEXT,
    description TEXT,
    created_at DATETIME NOT NULL,
    FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE,
    FOREIGN KEY (artifact_id) REFERENCES artifacts(id) ON DELETE CASCADE,
    FOREIGN KEY (step_id) REFERENCES goal_steps(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_goal_links_goal ON goal_artifact_links(goal_id);
CREATE INDEX IF NOT EXISTS idx_goal_links_artifact ON goal_artifact_links(artifact_id);
CREATE INDEX IF NOT EXISTS idx_goal_links_step ON goal_artifact_links(step_id);

-- ============================================================================
-- Judgment Layer: Decisions
-- ============================================================================

-- Tracks judgment decisions for learning and transparency
-- Action: suggest, remind, ask, stay_silent
-- Decision: speak (show to user), silent (suppress), ask (seek clarification)
CREATE TABLE IF NOT EXISTS judgment_decisions (
    id TEXT PRIMARY KEY,
    action TEXT NOT NULL CHECK(action IN ('suggest', 'remind', 'ask', 'stay_silent')),
    target_type TEXT NOT NULL CHECK(target_type IN ('suggestion', 'reminder', 'query')),
    target_id TEXT,
    decision TEXT NOT NULL CHECK(decision IN ('speak', 'silent', 'ask')),
    confidence REAL,
    reason TEXT,
    user_feedback TEXT CHECK(user_feedback IN ('helpful', 'intrusive', 'wrong', 'neutral') OR user_feedback IS NULL),
    created_at DATETIME NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_decisions_created ON judgment_decisions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_decisions_feedback ON judgment_decisions(user_feedback);
CREATE INDEX IF NOT EXISTS idx_decisions_target ON judgment_decisions(target_type, target_id);

-- ============================================================================
-- Judgment Layer: Quiet Hours
-- ============================================================================

-- User-configured quiet hours when no proactive suggestions/reminders are shown
-- day_of_week: 0 (Sunday) through 6 (Saturday)
-- hour_start, hour_end: 0-23 (24-hour format)
CREATE TABLE IF NOT EXISTS quiet_hours (
    id TEXT PRIMARY KEY,
    day_of_week INTEGER NOT NULL CHECK(day_of_week >= 0 AND day_of_week <= 6),
    hour_start INTEGER NOT NULL CHECK(hour_start >= 0 AND hour_start <= 23),
    hour_end INTEGER NOT NULL CHECK(hour_end >= 0 AND hour_end <= 23),
    enabled BOOLEAN DEFAULT TRUE,
    UNIQUE(day_of_week, hour_start, hour_end)
);

CREATE INDEX IF NOT EXISTS idx_quiet_hours_day ON quiet_hours(day_of_week, enabled);

-- ============================================================================
-- Project Schema Extensions
-- ============================================================================

-- Add columns to projects table for suggestion settings
-- suggestion_enabled: Opt-in for proactive suggestions (default FALSE)
-- suggestion_sensitivity: Confidence threshold for showing suggestions (0.0-1.0, default 0.7)
ALTER TABLE projects ADD COLUMN suggestion_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE projects ADD COLUMN suggestion_sensitivity REAL DEFAULT 0.7 CHECK(suggestion_sensitivity >= 0.0 AND suggestion_sensitivity <= 1.0);

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Tables Created: 8 total
--   - project_suggestions (4 indexes)
--   - action_patterns (3 indexes)
--   - project_activity_log (4 indexes)
--   - goals (5 indexes)
--   - goal_steps (2 indexes)
--   - goal_artifact_links (3 indexes)
--   - judgment_decisions (3 indexes)
--   - quiet_hours (1 index)
-- Columns Added:
--   - projects: suggestion_enabled, suggestion_sensitivity
-- Indexes Created: 25 total
-- Backward Compatibility: Full (all changes are additive, opt-in by default)
-- ============================================================================

-- Commit transaction
COMMIT;
